like_li=$('#like-solution-<%= @vote.solution_id %>')
like_li.find('a').tooltip('hide')
like_li.replaceWith('<%= vote_solution_link(votes_path(:solution_id => @vote.solution_id,:like => true),"post",@vote.solution_id,true,true) %>')
unlike_li=$('#unlike-solution-<%= @vote.solution_id %>')
unlike_li.find('a').tooltip('hide')
unlike_li.replaceWith('<%= vote_solution_link(votes_path(:solution_id => @vote.solution_id,:like => false),"post",@vote.solution_id,true,false) %>')
$('#solution-points-<%= @vote.solution_id %>').text('<%= @vote.solution( force_reload = true ).points %>分')
$('#solution-<%= @vote.solution_id %>').css("backgroundColor","#57A957").animate({backgroundColor:"#fff"},1500)
